name: Deploy MkDocs Site

on:
  push:
    branches: [main]
    paths:
      - 'mkdocs.yml'
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install MkDocs
        run: pip install mkdocs mkdocs-material mkdocstrings

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --remote-branch gh-pages
