site_name: EZ-FRCNN Documentation
site_url: https://ezfrcnn.com/mkdocs/
site_description: User guide and documentation for the EZ-FRCNN object detection system
site_author: Erin Shappell

# Output directory (optional — useful if embedding into Jekyll)
site_dir: mkdocs

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

# Optional: static files (e.g., images, js, css)
# Place these in a `docs/assets/` folder
extra_css:
  - assets/styles.css
extra_javascript:
  - assets/custom.js

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Training: training.md
  - Exporting Results: exporting.md
  - FAQ: faq.md
  - GitHub: https://github.com/lu-lab/ez-frcnn

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.keys

plugins:
  - search
